sudo: required
services:
    - docker

before_install:
    docker build -it Sanooja997/docker-react -f Dockerfile.dev .

script:
    docker run -e CI-=true Sanooja456/docker-react npm run test -- --coverage