sudo: required
services:
    - docker

before_install:
    docker build -t san456/docker-react -f Dockerfile.dev .

script:
<<<<<<< HEAD
    docker run -e CI-=true san456/docker-react npm run test

deploy:
    provider: elastisbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-885739190592"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        
    
    
    
    
=======
    docker run -e CI=true san456/docker-react npm run test
>>>>>>> ca3ba7909dbd0295baaf0567f282cf264953b51e
